apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: team-alpha
type: Opaque
data:
  mysql_root_pass: cGFzcw==
  mysql_database: ZGF0YWJhc2U=
  mysql_user: dXNlcm5hbWU=
  mysql_password: cGFzc3dvcmQ=
