apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: team-alpha
type: Opaque
data:
  mysql_root_pass: {{ .Values.secrets.mysqlRootPassword }}
  mysql_database: {{ .Values.secrets.mysqlDatabase }}
  mysql_user: {{ .Values.secrets.mysqlUser }}
  mysql_password: {{ .Values.secrets.mysqlPassword }}
