apiVersion: v1
kind: Service
metadata:
  name: webapp-sql
  namespace: team-alpha
spec:
  selector:
    app: webapp-sql
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: NodePort