apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: team-alpha
  labels:
    app: webapp-sql
    tier: frontend
spec:
  selector:
    matchLabels:
      app: webapp-sql
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp-sql
        tier: frontend
    spec:
      containers:
      - name: webapp1
        image: dockerloginpage/frontend:v1.0.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mysql_root_pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mysql_database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mysql_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: mysql_password
        - name: MYSQL_ROOT_HOST
          value: mysql-svc
        imagePullPolicy: Always
        ports:
        - containerPort: 80