apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.app }}
    tier: {{ .Values.backend.tier }}
  ports:
  - protocol: "TCP"
    port: {{ .Values.backendService.port }}
    targetPort: {{ .Values.backendService.port }}
  clusterIP: {{ .Values.backendService.clusterIP }}
