kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage-volume-sc
provisioner: kubernetes.io/host-path  # Example provisioner for hostPath volumes
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer